name: update rules

on:
  push:
    branches: [ main ]

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pyyaml

    - name: Run app
      run: python run.py
      
    # Commit all changed files back to the repository
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0


    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
